# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tryit',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='small_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
