# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160801_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tryit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
