# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160801_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
