# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutme',
            new_name='Post',
        ),
    ]
