# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20160804_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
